@baseUrl=http://localhost:5000
@urlPath = api/v1



###
PUT {{baseUrl}}/{{urlPath}}/user/follow/68970944a1119197491ba82f
Content-Type: application/json
Accept: application/json
withCredentials: true

{}


###
PUT {{baseUrl}}/{{urlPath}}/user/unfollow/6888cf9ee0b759f0def369d2/688b67212b2d2139a8102199
Content-Type: application/json
Accept: application/json
withCredentials: true

{}


###
GET {{baseUrl}}/{{urlPath}}/user/following
Content-Type: application/json
Accept: application/json
withCredentials: true



###
PUT {{baseUrl}}/{{urlPath}}/user/block/688a547d074d8bc594a256d6
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
