@baseUrl=http://localhost:5000
@urlPath = api/v1


###
PUT {{baseUrl}}/{{urlPath}}/notification/688ce8190c65897b58b07b47
Content-Type: application/json
Accept: application/json
withCredentials: true

{}


###
DELETE {{baseUrl}}/{{urlPath}}/notification/688ce8190c65897b58b07b47
Content-Type: application/json
Accept: application/json
withCredentials: true

{}


###
GET  {{baseUrl}}/{{urlPath}}/notification
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
