@baseUrl=http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "post":"This is my first post",
"bgColor":"#4aa1f3",
"privacy":"Public",
"gifUrl":"",
"profilePicture": "https://res.cloudinary.com/dtncgifkk/image/upload/v1753350357/688200d37428834af0839965",
"feelings":"happy"
}
