@baseUrl=http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo":"688a547d074d8bc594a256d6",
"postId":"688a38c86962fd259ac203c5",
"type":"sad",
"previousReaction":"",
"postReactions":{"like": 0,"love": 0,"happy": 0,"sad": 1,"wow": 0,"angry": 0},
"profilePicture": "https://res.cloudinary.com/dtncgifkk/image/upload/v1753350357/688200d37428834af0839965"
}


###
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/688a38c86962fd259ac203c5/happy/{"like": 0,"love": 0,"happy": 0,"sad": 0,"wow": 0,"angry": 0}
Content-Type: application/json
Accept: application/json
withCredentials: true

{}



###
GET {{baseUrl}}/{{urlPath}}/post/reactions/688a38c86962fd259ac203c5
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/post/single/reaction/username/Danny/688a38c86962fd259ac203c5
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/post/reactions/username/Manny
Content-Type: application/json
Accept: application/json
withCredentials: true
